/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -t shirt_baked.glb
*/

import { canvasState } from "@/store/canvasState";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { useSnapshot } from "valtio";

type GLTFResult = GLTF & {
  nodes: {
    T_Shirt_male: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
  };
};

export function ShirtModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/model/shirt_baked.glb") as GLTFResult;

  const state = useSnapshot(canvasState);
  const logoTextureState = state.logoTexture;
  const fullTextureState = state.fullTexture;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.T_Shirt_male.geometry}
        material={materials.lambert1}
      />
    </group>
  );
}

useGLTF.preload("/shirt_baked.glb");
